

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  flask:
    build: .
    container_name: flask-api-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0  # 👈 This is the fix
